# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  # mainブランチにプッシュされたら実行する（masterブランチの場合は変更してください）
  push:
    branches: [master]
  # GitHub Actionsのタブから手動で実行できるようにする
  workflow_dispatch:

# 権限の設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3

        with:
          node-version: 22
          package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
